name: "My first actions workflow"

on:
  push:
    branches:
      - master

jobs:
  my-first-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: My first step
        run: echo "My first step"

      - name: Correr Pruebas
        run: echo "Correr Pruebas"

      - name: Ver si todo funciona
        run: echo "Ver si todo funciona ${{ secrets.ONLINE_VALUE_ENV}}"

      - name: Imprimir variable secreta
        run: echo "El valor del secreto es ${{ github.ref }}"
  run-test-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn test