name: "My first actions workflow"

on:
  push:
    branches:
      - master

jobs:
  my-first-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: My first step
        run: echo "My first step"

      - name: Correr Pruebas
        run: echo "Correr Pruebas"

      - name: Ver si todo funciona
        run: echo "Ver si todo funciona"

      - name: Imprimir variable secreta
        run: echo "El valor del secreto es ${{ secrets.ONLINE_VALUE_ENV }}"
